webapp/app/components/Navigator/Navigator.less
webapp/app/containers/Dashboard/Grid.js

globalFilter fix，多个 filter 影响同个 dashboardItem 时逻辑目前可以叠加

---

webapp/app/assets/json/widgetlib/area.json
webapp/app/assets/json/widgetlib/bar.json
webapp/app/assets/json/widgetlib/boxplot.json
webapp/app/assets/json/widgetlib/doubleYAxis.json
webapp/app/assets/json/widgetlib/funnel.json
webapp/app/assets/json/widgetlib/line.json
webapp/app/assets/json/widgetlib/markBoxplot.json
webapp/app/assets/json/widgetlib/pie.json
webapp/app/assets/json/widgetlib/scatter.json
webapp/app/assets/json/widgetlib/wordCloud.json
webapp/app/containers/Bizlogic/sagas.js
webapp/app/containers/Dashboard/Grid.js
webapp/app/containers/Dashboard/components/globalFilter/GlobalFilterConfigPanel.js
webapp/app/containers/Dashboard/components/globalFilter/ItemSelectorForm.js
webapp/app/containers/Dashboard/reducer.js
webapp/app/containers/Widget/charts/area.js
webapp/app/containers/Widget/charts/bar.js
webapp/app/containers/Widget/charts/boxplot.js
webapp/app/containers/Widget/charts/doubleYAxis.js
webapp/app/containers/Widget/charts/funnel.js
webapp/app/containers/Widget/charts/line.js
webapp/app/containers/Widget/charts/markBoxplot.js
webapp/app/containers/Widget/charts/pie.js
webapp/app/containers/Widget/charts/scatter.js
webapp/app/containers/Widget/charts/wordCloud.js
webapp/package.json

新增图例默认全选与全不选
新增 globalFilter 初步对变量的支持（未完善）
将 react-color 添加到项目依赖

新增图例默认全选与全不选；新增 globalFilter 初步对变量的支持（未完善）

---

webapp/app/assets/json/widgetlib/sankey.json
webapp/app/containers/Widget/charts/sankey.js

feat(widget): add available widget type sankey
issues: https://github.com/edp963/davinci/issues/158

feat(widget): add available widget type sankey

---

webapp/app/containers/Widget/actions.ts
webapp/app/containers/Widget/components/Workbench.tsx
webapp/app/containers/Widget/index.tsx
webapp/app/containers/Widget/reducer.ts
webapp/app/containers/Widget/sagas.ts
webapp/app/containers/Widget/selectors.ts

1. remove duplicate actions/sagas/reducer/selector of `bizlogic` in module `Widget`

refactor(widget): remove duplicate code

---

bin/build.sh
bin/davinci.sql
bin/initdb.sh
bin/run.bat
bin/start.bat
bin/stop.bat
server/src/main/resources/application.yml

新增Windows环境启动脚本
新增初始化数据表脚本
修改配置项

新增Windows环境启动脚本

---

bin/run.bat
bin/start-server.sh
server/src/main/java/edp/core/enums/DataTypeEnum.java
server/src/main/java/edp/core/utils/SqlUtils.java
server/src/main/java/edp/davinci/common/service/CommonService.java
server/src/main/java/edp/davinci/core/common/ResultMap.java
server/src/main/java/edp/davinci/service/impl/OrganizationServiceImpl.java
server/src/main/java/edp/davinci/service/impl/ProjectServiceImpl.java
server/src/main/java/edp/davinci/service/impl/ViewServiceImpl.java
server/src/main/resources/templates/mail/inviteOrgMemberTemplate.html
server/src/main/resources/templates/sql/sqlTemplate.stg

1. 修改默认数据源查询表结构语句，根据方言对保留字进行处理
2. 修改启动脚本
3. 修改单个字段distinct查询返回结构
4. 修改组织邀请成员邮件模板UI
5. 修复一些bug

修改jdbc数据源查询结构语句，修改启动脚本

---

server/src/main/java/edp/core/utils/QuartzUtils.java
server/src/main/java/edp/davinci/controller/ShareController.java
server/src/main/java/edp/davinci/dao/CronJobMapper.java
server/src/main/java/edp/davinci/dao/UserMapper.java
server/src/main/java/edp/davinci/dto/shareDto/ShareInfo.java
server/src/main/java/edp/davinci/runner/CronJobRunner.java
server/src/main/java/edp/davinci/service/CronJobService.java
server/src/main/java/edp/davinci/service/ShareService.java
server/src/main/java/edp/davinci/service/ViewService.java
server/src/main/java/edp/davinci/service/WidgetService.java
server/src/main/java/edp/davinci/service/impl/CronJobServiceImpl.java
server/src/main/java/edp/davinci/service/impl/EmailScheduleServiceImpl.java
server/src/main/java/edp/davinci/service/impl/ShareServiceImpl.java
server/src/main/java/edp/davinci/service/impl/ViewServiceImpl.java
server/src/main/java/edp/davinci/service/impl/WidgetServiceImpl.java
server/src/main/resources/mybatis/mapper/CronJobMapper.xml
server/src/main/resources/templates/mail/scheduleEmaiTemplate.html

1.  添加Share全局过滤DistinctValue
2. 修改CronJob

Server添加Share全局过滤DistinctValue

---

webapp/app/containers/Display/Editor.tsx
webapp/app/containers/Display/components/DisplayHeader.tsx
webapp/app/containers/Display/components/LayerItem.tsx
webapp/app/containers/Display/reducer.ts
webapp/share/containers/Display/actions.ts
webapp/share/containers/Display/index.tsx
webapp/share/containers/Display/reducer.ts
webapp/share/containers/Display/sagas.ts
webapp/share/containers/Display/selectors.ts

1. fix Display SharePanel error 
2. fix Display Share page errors

fix(Display): fix Display SharePanel error and Display Share page errors

---

webapp/app/components/Linkages/LinkageConfig.tsx
webapp/app/components/Linkages/LinkageForm.tsx
webapp/app/components/Linkages/index.ts
webapp/app/containers/Dashboard/Grid.tsx
webapp/app/containers/Dashboard/components/DashboardItem.tsx
webapp/app/containers/Dashboard/components/DashboardLinkageConfig.tsx
webapp/app/containers/Dashboard/components/DashboardToolbar.tsx
webapp/app/containers/Dashboard/selectors.ts
webapp/app/containers/Display/components/SettingForm.tsx
webapp/app/containers/Widget/components/util.ts
webapp/app/utils/operatorTypes.ts
webapp/share/containers/Dashboard/actions.ts
webapp/share/containers/Dashboard/index.tsx
webapp/share/containers/Dashboard/reducer.ts
webapp/share/containers/Dashboard/sagas.ts
webapp/share/containers/Dashboard/selectors.ts
webapp/tsconfig.json

1. fix Display Secondary Layer Label SettingForm label content input edit bug, change to PressEnter handler  
2. add Linkage config components and Linkage feature in Dashboard and its share page
3. fix Widget tooltip position with cover Linkage click bug

feat. Linkage and bugs fixed

---

bin/start-server.sh
config/application.yml.example
server/src/main/java/edp/davinci/service/impl/EmailScheduleServiceImpl.java
server/src/main/java/edp/davinci/service/impl/OrganizationServiceImpl.java
server/src/main/java/edp/davinci/service/impl/ShareServiceImpl.java
server/src/main/java/edp/davinci/service/impl/UserServiceImpl.java
server/src/main/java/edp/davinci/service/impl/WidgetServiceImpl.java

1. 优化启动脚本
2. 修复成员接受组织邀请bug
3. 修复文件生成文件bug

优化启动脚本，修复一些bug

---

webapp/app/assets/json/slideSettings/chart.json
webapp/app/assets/json/slideSettings/label.json
webapp/app/assets/json/slideSettings/rectangle.json
webapp/app/assets/json/slideSettings/video.json
webapp/app/components/Filters/FilterForm.tsx
webapp/app/components/Filters/FilterPanel.tsx
webapp/app/containers/Dashboard/Grid.tsx
webapp/app/containers/Display/Display.less
webapp/app/containers/Display/Editor.tsx
webapp/app/containers/Display/components/LayerItem.tsx
webapp/app/containers/Display/components/SettingForm.tsx
webapp/app/containers/Widget/components/Chart/Chart.less
webapp/app/containers/Widget/components/Chart/Scorecard.tsx
webapp/app/containers/Widget/components/Workbench/index.tsx
webapp/app/containers/Widget/index.tsx

fix Widget Display Filter bugs

---

server/src/main/java/edp/core/enums/DataTypeEnum.java
server/src/main/java/edp/davinci/dao/UserMapper.java
server/src/main/java/edp/davinci/dto/sourceDto/SourceConfig.java
server/src/main/java/edp/davinci/dto/sourceDto/SourceTest.java

1. fix datasource test connection、 alias prefix and suffix
2. fix user login

fix datasource

---

webapp/app/containers/Widget/components/Chart/Scorecard.tsx
webapp/app/containers/Widget/components/Workbench/OperatingPanel.tsx

fix widget edit bugs

---

bin/davinci.sql
server/src/main/java/edp/core/utils/RedisUtils.java
server/src/main/java/edp/davinci/controller/AuthPlatformController.java
server/src/main/java/edp/davinci/controller/TeamController.java
server/src/main/java/edp/davinci/controller/ViewController.java
server/src/main/java/edp/davinci/core/inteceptor/PlatformAuthInterceptor.java
server/src/main/java/edp/davinci/core/utils/CsvUtils.java
server/src/main/java/edp/davinci/dto/platform/VizTokenDto.java
server/src/main/java/edp/davinci/model/MemDashboardWidget.java
server/src/main/java/edp/davinci/service/AuthPlatformService.java
server/src/main/java/edp/davinci/service/TeamService.java
server/src/main/java/edp/davinci/service/TeamVarService.java
server/src/main/java/edp/davinci/service/impl/TeamServiceImpl.java

1. Dashboard widget 关联类加config字段
2. 生成csv加bom头，解决excel打开csv乱码问题
3. 修改Platform相关接口实现
4. 新增字段

fix Dashboard and Platform

---

webapp/app/containers/Dashboard/Grid.tsx
webapp/app/containers/Dashboard/components/DashboardItem.tsx
webapp/app/containers/Widget/components/Chart/Chart.less
webapp/app/containers/Widget/components/Chart/Table.tsx
webapp/app/containers/Widget/components/Widget/index.tsx
webapp/app/containers/Widget/components/Workbench/ConfigSections/TableSection/index.tsx
webapp/app/containers/Widget/components/Workbench/ConfigSections/TableSection/util.tsx
webapp/app/containers/Widget/components/Workbench/OperatingPanel.tsx
webapp/app/containers/Widget/components/Workbench/index.tsx
webapp/app/containers/Widget/config/chart/table.ts
webapp/app/globalConstants.ts

1. WIP: Table pagination
2. fix Table cell style bug

feat(Widget): Table pagination

---

webapp/app/containers/Dashboard/components/DashboardItem.tsx
webapp/app/containers/Widget/components/Chart/Chart.less
webapp/app/containers/Widget/components/Chart/Scorecard.tsx
webapp/app/containers/Widget/components/Chart/Table.tsx
webapp/app/containers/Widget/components/Workbench/ConfigSections/IframeSection.tsx
webapp/app/containers/Widget/components/Workbench/ConfigSections/TableSection/index.tsx
webapp/app/containers/Widget/components/Workbench/index.tsx
webapp/app/containers/Widget/render/chart/parallel.ts
webapp/app/containers/Widget/render/chart/radar.ts
webapp/app/containers/Widget/render/chart/sankey.ts

fix Widget&Dashboard bugs

---

server/src/main/java/edp/core/config/RedisConfig.java
server/src/main/java/edp/core/model/Paginate.java

1. fix RedisTemplate default serializer
2. Paginate implement Serializable interface

fix redis cache

---

webapp/app/assets/less/resizer.less
webapp/app/containers/Widget/components/Chart/Chart.less
webapp/app/containers/Widget/components/Chart/Table.tsx
webapp/app/containers/Widget/components/Workbench/ConfigSections/TableSection/index.tsx
webapp/app/containers/Widget/components/Workbench/FieldConfig/index.tsx
webapp/app/containers/Widget/components/Workbench/Workbench.less
webapp/app/containers/Widget/components/Workbench/index.tsx
webapp/package.json

1. add Workbench pane split, localStorage split size
2. Widget Table only merges dimension cells across rows
3. update Table header config column display name

Workbench update

---

server/src/main/java/edp/davinci/core/utils/ExcelUtils.java
server/src/main/resources/templates/js/formatCellValue.js

1. 修改下载Excel queryVar 动态列名Bug
2. 修改升级脚本

fix dev-0.3

---

webapp/app/containers/Background/Canvas.tsx
webapp/app/containers/Widget/components/computedConfigForm.tsx
webapp/app/index.html
webapp/internals/webpack/webpack.base.babel.js
webapp/package-lock.json
webapp/package.json

1. upgrade threejs to fix `node_modules/three` export bug in previous version
2. refactor login page to using webGL render in threejs
3. add threejs import code split 
4. fix `moment` locale file dynamic require webpack bundle warning after `cnpm i`
5. fix import file path name differs in casing

update performance & fix webpack bundle warning

---

webapp/app/assets/less/style.less
webapp/app/containers/Display/Display.less
webapp/app/containers/Main/Main.less
webapp/app/index.html

Revert "style: update #app style"

---

server/src/main/java/edp/core/utils/SqlUtils.java

Issue: https://github.com/edp963/davinci/issues/812

fix(View): fix the field name error when use the 'AS' keyword to alias column name in SQL

---

webapp/app/containers/Widget/components/Chart/Chart.less
webapp/app/containers/Widget/components/Chart/Table.tsx
webapp/app/containers/Widget/components/Workbench/ConfigSections/TableSection/HeaderConfigModal.tsx

Antd Table Header sorter render changed since Antd 3.16.0, by upgrading antd from 3.11.0 to 3.17.0.  
Remove sorter temporarily.

fix(Widget): fix Table style & header default transparent & remove sorter

---

server/src/main/java/edp/core/utils/SqlUtils.java
server/src/main/resources/banner.txt

1. get count sql
2. fix banner springboot version

Dev 0.3 fix

---

.gitignore
server/src/main/java/edp/davinci/service/impl/ViewServiceImpl.java
server/src/main/java/edp/davinci/service/impl/WidgetServiceImpl.java

fix permission check

---

webapp/app/components/Filters/FilterPanel.tsx
webapp/app/components/Filters/config/FilterList.tsx
webapp/app/components/Filters/index.tsx
webapp/app/containers/Dashboard/components/DashboardItemControlForm.tsx
webapp/app/containers/Display/Editor.tsx
webapp/app/containers/Display/Preview.tsx
webapp/app/containers/Display/reducer.ts
webapp/app/containers/Widget/components/Workbench/ControlConfig.tsx
webapp/share/containers/Display/index.tsx
webapp/share/containers/Display/reducer.ts
webapp/share/containers/Display/sagas.ts

fix: tempFilters in display;
fix: global & local control type conflict

Fix: display and control bugs

---

webapp/.gitignore
webapp/app/containers/View/index.tsx

1.  add .gitignore for .history files
2. fix view list display problem

fix view list display problem

---

webapp/app/utils/util.ts
webapp/share/containers/Dashboard/sagas.ts

Fix: widget authorize share

---

webapp/app/containers/Organizations/Organization.less
webapp/app/containers/Organizations/Organization.tsx
webapp/app/containers/Organizations/component/ChangeRoleForm.tsx
webapp/app/containers/Organizations/component/MemberList.tsx
webapp/app/containers/Organizations/component/ProjectAdmin.tsx
webapp/app/containers/Organizations/component/ProjectAuth.tsx
webapp/app/containers/Organizations/component/ProjectRole.tsx
webapp/app/containers/Organizations/component/RoleList.tsx

Fix: organization role setting actions permission bug;

---

bin/patch/001_beta5.sql
server/src/main/java/edp/core/consts/Consts.java
server/src/main/java/edp/core/utils/SqlUtils.java
server/src/main/java/edp/davinci/controller/DownloadController.java
server/src/main/java/edp/davinci/core/common/Constants.java
server/src/main/java/edp/davinci/core/utils/SqlParseUtils.java
server/src/main/java/edp/davinci/dao/DashboardMapper.java
server/src/main/java/edp/davinci/service/excel/AbstractSheetWriter.java
server/src/main/java/edp/davinci/service/excel/SheetWorker.java
server/src/main/java/edp/davinci/service/impl/ViewServiceImpl.java
server/src/main/resources/templates/js/executeParam.js

1. get data
2. download
3. auth param

Dev-0.3 fix bug

---

server/src/main/java/edp/davinci/core/utils/SqlParseUtils.java
server/src/main/java/edp/davinci/service/impl/ShareServiceImpl.java
server/src/main/java/edp/davinci/service/impl/ViewServiceImpl.java
server/src/main/resources/mybatis/mapper/ProjectMapper.xml

1. fix share download
2. fix auth variable in get data
3. fix get projects sql

Dev0.3 fix

---

webapp/app/components/Filters/FilterControl.tsx
webapp/app/components/Filters/FilterPanel.tsx
webapp/app/components/Filters/config/FilterConfig.tsx
webapp/app/components/Filters/filter.less
webapp/app/components/Filters/index.tsx
webapp/app/components/Filters/types.ts
webapp/app/containers/App/actions.ts
webapp/app/containers/App/constants.ts
webapp/app/containers/App/sagas.ts
webapp/app/containers/App/types.ts
webapp/app/containers/Dashboard/Grid.tsx
webapp/app/containers/Dashboard/actions.ts
webapp/app/containers/Dashboard/components/DashboardForm.tsx
webapp/app/containers/Dashboard/components/DashboardToolbar.tsx
webapp/app/containers/Dashboard/constants.ts
webapp/app/containers/Dashboard/index.tsx
webapp/app/containers/Dashboard/reducer.ts
webapp/app/containers/Dashboard/types.ts

Feat: global control query mode support

Feat: async download done

---

server/src/main/java/edp/davinci/dao/RelRoleDashboardMapper.java
server/src/main/java/edp/davinci/dao/RelRoleDisplayMapper.java
server/src/main/java/edp/davinci/dao/RelRolePortalMapper.java
server/src/main/java/edp/davinci/dao/RelRoleSlideMapper.java
server/src/main/java/edp/davinci/service/impl/ViewServiceImpl.java

1. fix viz role
2. fix query data auth variable bug

fix role bug

---

server/src/main/java/edp/davinci/controller/ProjectController.java
server/src/main/java/edp/davinci/dao/RelProjectAdminMapper.java
server/src/main/java/edp/davinci/service/ProjectService.java
server/src/main/java/edp/davinci/service/impl/CronJobServiceImpl.java
server/src/main/java/edp/davinci/service/impl/ProjectServiceImpl.java
server/src/main/resources/mybatis/mapper/RelProjectAdminMapper.xml

1. fix project add admins
2. delete flag in stop cronjob by redis message receiver

Dev0.3 Server fix

---

server/src/main/java/edp/core/utils/FileUtils.java
server/src/main/java/edp/core/utils/MailUtils.java
server/src/main/java/edp/davinci/dto/cronJobDto/ExcelContent.java
server/src/main/java/edp/davinci/dto/cronJobDto/MsgMailExcel.java
server/src/main/java/edp/davinci/service/excel/MsgNotifier.java
server/src/main/java/edp/davinci/service/excel/WidgetContext.java
server/src/main/java/edp/davinci/service/excel/WorkBookContext.java
server/src/main/java/edp/davinci/service/excel/WorkbookWorker.java
server/src/main/java/edp/davinci/service/impl/EmailScheduleServiceImpl.java

Cronjob send email modify asynchronously generate excel and email excel attachment name

Dev 0.3 Modify asynchronously generate excel in cronjob

---

server/src/main/java/edp/core/common/jdbc/JdbcDataSource.java
server/src/main/java/edp/core/common/jdbc/QueryTimeOutStatementCreator.java
server/src/main/java/edp/core/consts/Consts.java
server/src/main/java/edp/core/utils/SqlUtils.java
server/src/main/java/edp/davinci/service/excel/SheetWorker.java
server/src/main/java/edp/davinci/service/impl/CronJobHandler.java
server/src/main/java/edp/davinci/service/impl/CronJobServiceImpl.java

1. SqlUtils add get sql 'FromItem' method
2. Fix some datasource query result column name with table problem
3. Fix some datasource download excel no data problem
4. Fix delete flag after stop cronjob

Dev-0.3 Fix

---

server/src/main/java/edp/core/common/jdbc/ESDataSource.java
server/src/main/java/edp/core/common/jdbc/JdbcDataSource.java
server/src/main/java/edp/core/enums/DataTypeEnum.java
server/src/main/java/edp/core/utils/SourceUtils.java
server/src/main/java/edp/core/utils/SqlUtils.java
server/src/main/java/edp/davinci/core/enums/SqlColumnEnum.java
server/src/main/java/edp/davinci/dao/ProjectMapper.java
server/src/main/java/edp/davinci/service/impl/ProjectServiceImpl.java
server/src/main/resources/mybatis/mapper/ProjectMapper.xml

1. Elasticsearch datasource properties
2. Upload data format value
3. Transfer project delete origin organization relation record

Dev-0.3 bug fix

---

server/pom.xml
server/src/main/java/edp/core/common/jdbc/JdbcDataSource.java
server/src/main/java/edp/core/utils/SourceUtils.java
server/src/main/java/edp/core/utils/SqlUtils.java

1. JdbcDataSource no longer extends DruidDataSource
2. upgrade fastjson version #1118

fix: fix init datasource and upgrade fastjson version

---

webapp/app/containers/Dashboard/Grid.tsx
webapp/app/containers/Organizations/component/ProjectForm.tsx
webapp/app/utils/statistic/monitoredAction.ts
webapp/app/utils/statistic/statistic.dv.ts
webapp/share/containers/Dashboard/index.tsx

1.add linkagefilter and globalfilter
2.add all variables

fix: fix statistic add widget details

---

server/src/main/java/edp/core/common/jdbc/ESDataSource.java
server/src/main/java/edp/core/utils/CustomDataSourceUtils.java
server/src/main/java/edp/core/utils/SourceUtils.java
server/src/main/java/edp/davinci/controller/SourceController.java
server/src/main/java/edp/davinci/model/RelRoleProject.java
server/src/main/java/edp/davinci/service/SourceService.java
server/src/main/java/edp/davinci/service/excel/ExecutorUtil.java
server/src/main/java/edp/davinci/service/excel/WorkbookWorker.java
server/src/main/java/edp/davinci/service/impl/CronJobServiceImpl.java
server/src/main/java/edp/davinci/service/impl/DownloadServiceImpl.java
server/src/main/java/edp/davinci/service/impl/EmailScheduleServiceImpl.java
server/src/main/java/edp/davinci/service/impl/ShareDownloadServiceImpl.java
server/src/main/java/edp/davinci/service/impl/SourceServiceImpl.java

1. fix datasource versions list
2. fix member default project permission
3. add log for download task and email schedule
4. add release and reconnect source API

fix: fix datasource version, default project permission, add log

---

server/src/main/java/edp/davinci/common/utils/ScriptUtiils.java
server/src/main/java/edp/davinci/service/impl/ViewServiceImpl.java
server/src/main/resources/templates/js/executeParam.js

fix filter bug

---

server/src/main/java/edp/davinci/service/impl/ViewServiceImpl.java

update convertFilters output log

update convertFilters output log

---

server/src/main/java/edp/davinci/core/common/Constants.java
server/src/main/java/edp/davinci/core/enums/SqlVariableValueTypeEnum.java
server/src/main/java/edp/davinci/core/utils/SqlParseUtils.java
server/src/main/java/edp/davinci/service/impl/ViewServiceImpl.java

update ST authParamMap

---

webapp/app/containers/Schedule/components/ScheduleMailConfig.tsx
webapp/app/containers/View/components/SourceTable.tsx
webapp/app/containers/Widget/components/Workbench/OperatingPanel.tsx
webapp/app/containers/Widget/components/Workbench/Workbench.less

fix: select search style in View&Widget edit

---

webapp/app/containers/Widget/components/Workbench/FilterSettingForm.tsx

Fix: year dynamic date widget filter bug

---

webapp/app/containers/App/actions.ts
webapp/app/containers/App/reducer.ts
webapp/app/containers/App/sagas.ts
webapp/app/containers/Login/index.tsx
webapp/app/containers/Profile/index.tsx

fix: profile info is modified and saved，no changed on page #1231

---

server/src/main/java/edp/core/model/BaseSource.java
server/src/main/java/edp/core/model/JdbcSourceInfo.java
server/src/main/java/edp/core/utils/RedisUtils.java
server/src/main/java/edp/davinci/dao/SourceMapper.java
server/src/main/java/edp/davinci/dao/UserMapper.java
server/src/main/java/edp/davinci/dto/sourceDto/SourceTest.java
server/src/main/java/edp/davinci/model/Source.java
server/src/main/java/edp/davinci/service/impl/CheckServiceImpl.java
server/src/main/java/edp/davinci/service/impl/SourceMessageHandler.java
server/src/main/java/edp/davinci/service/impl/SourceServiceImpl.java

#1399 
1. new component redis lock  
2. fix Source "isExist" issue

source "isExist" in cluster mode not work

---

server/src/main/java/edp/core/utils/BaseLock.java
server/src/main/java/edp/core/utils/LockFactory.java
server/src/main/java/edp/core/utils/RedisUtils.java
server/src/main/java/edp/davinci/core/enums/LockType.java
server/src/main/java/edp/davinci/service/impl/SourceServiceImpl.java

you can get a lock with ttl easily by use "LockFactory"

add "LockFactory" component

---

webapp/app/containers/Dashboard/components/DashboardForm.tsx
webapp/app/containers/Dashboard/index.tsx

Fix: cann't get child route params from parent route component in react-router 5

Fix: cann't get child route params from parent route component

---

server/src/main/java/edp/davinci/dto/dashboardDto/MemDashboardWidgetCreate.java
server/src/main/java/edp/davinci/service/impl/BaseEntityService.java
server/src/main/java/edp/davinci/service/impl/CronJobMessageHandler.java
server/src/main/java/edp/davinci/service/impl/CronJobServiceImpl.java
server/src/main/java/edp/davinci/service/impl/DashboardPortalServiceImpl.java
server/src/main/java/edp/davinci/service/impl/DashboardServiceImpl.java
server/src/main/java/edp/davinci/service/impl/SourceServiceImpl.java
server/src/main/java/edp/davinci/service/impl/VizCommonService.java

fix "DashboardPortal" & "Dashboard" model isExist issue

---

webapp/app/containers/Display/Editor/Header.tsx

for fix currentProject widgets cache not valid bug

fix(Display): temporarily not use widgets cache

---

bin/patch/beta.sql
server/src/main/java/edp/core/consts/Consts.java
server/src/main/java/edp/davinci/core/utils/ExcelUtils.java
server/src/main/java/edp/davinci/dao/DisplayMapper.java
server/src/main/java/edp/davinci/dao/DisplaySlideMapper.java
server/src/main/java/edp/davinci/dao/WidgetMapper.java
server/src/main/java/edp/davinci/dto/dashboardDto/DashboardTree.java
server/src/main/java/edp/davinci/dto/displayDto/DisplayInfo.java
server/src/main/java/edp/davinci/dto/displayDto/DisplayUpdate.java
server/src/main/java/edp/davinci/dto/shareDto/ShareDisplay.java
server/src/main/java/edp/davinci/dto/viewDto/ViewExecuteParam.java
server/src/main/java/edp/davinci/model/Display.java
server/src/main/java/edp/davinci/runner/CronJobRunner.java
server/src/main/java/edp/davinci/service/excel/AbstractSheetWriter.java
server/src/main/java/edp/davinci/service/impl/DisplayServiceImpl.java
server/src/main/java/edp/davinci/service/impl/EmailScheduleServiceImpl.java
server/src/main/java/edp/davinci/service/impl/ShareServiceImpl.java
server/src/main/resources/mybatis/mapper/DashboardMapper.xml
server/src/main/resources/mybatis/mapper/DisplayMapper.xml

feature: 
1. share display add config field
2. start job runner enable config
fix: 
1. excel number format
2. schedule excel display query first slide
3. schedule screenshot order error

Merge to dev-0.3

---

server/src/main/java/edp/davinci/service/impl/BaseEntityService.java
server/src/main/java/edp/davinci/service/impl/DisplayServiceImpl.java
server/src/main/java/edp/davinci/service/impl/VizCommonService.java

fix "dispaly" model isExist issue

---

server/src/main/java/edp/davinci/core/enums/CheckEntityEnum.java
server/src/main/java/edp/davinci/core/enums/VizEnum.java
server/src/main/java/edp/davinci/dao/DisplaySlideMapper.java
server/src/main/java/edp/davinci/dao/MemDisplaySlideWidgetMapper.java
server/src/main/java/edp/davinci/service/impl/BaseEntityService.java
server/src/main/java/edp/davinci/service/impl/DisplayServiceImpl.java
server/src/main/java/edp/davinci/service/impl/DisplaySlideServiceImpl.java
server/src/main/java/edp/davinci/service/impl/VizCommonService.java

fix "displaySlide" model isExist issue

---

server/src/main/java/edp/davinci/service/impl/BaseEntityService.java
server/src/main/java/edp/davinci/service/impl/OrganizationServiceImpl.java
server/src/main/java/edp/davinci/service/impl/ProjectServiceImpl.java

fix "organization" & "project" model isExist issue

---

server/src/main/java/edp/davinci/service/impl/BaseEntityService.java
server/src/main/java/edp/davinci/service/impl/WidgetServiceImpl.java

fix "widget" model isExist issue

---

config/application.yml.example
server/src/main/java/edp/davinci/dao/DisplaySlideMapper.java
server/src/main/java/edp/davinci/dao/WidgetMapper.java
server/src/main/java/edp/davinci/runner/CronJobRunner.java
server/src/main/java/edp/davinci/service/impl/CronJobServiceImpl.java
server/src/main/java/edp/davinci/service/impl/EmailScheduleServiceImpl.java
server/src/main/resources/mybatis/mapper/DisplaySlideMapper.xml

1. schedule support multi-slide
2. update configuration example
3. fix start all jobs runner

feature: schedule support multi-slides

---

webapp/app/utils/request.ts
webapp/share/containers/App/index.tsx
webapp/share/containers/Dashboard/index.tsx

Fix auth share lost login state

---

webapp/app/containers/Widget/render/chart/funnel.ts
webapp/app/containers/Widget/render/chart/pie.ts

fix: pie and funnel color config bugs temporarily

---

webapp/app/containers/Widget/render/chart/map.ts

fix: province data with suffix can not encode correctly in regular map

---

webapp/app/containers/View/util.ts

fix: geo visual type execute sql bug

---

server/src/main/java/edp/core/utils/SqlUtils.java
server/src/main/java/edp/davinci/core/inteceptor/AuthenticationInterceptor.java
server/src/main/java/edp/davinci/service/impl/DisplaySlideServiceImpl.java

1. fix add sub widget "Invalid Widget Id" error in display page  #1514
2. modify some log levels

hotfix: fix add sub widget "Invalid Widget Id" error in display page

---

server/src/main/java/edp/davinci/service/impl/ShareDownloadServiceImpl.java

(cherry picked from commit 7d6208e2fd0ee700adde875c30d84b76d9de5d47)

hotfix: fix share page download error

---

webapp/share/containers/Dashboard/reducer.ts

fix: global control custom options lost in share page

---

webapp/app/containers/Dashboard/Grid.tsx
webapp/share/containers/Dashboard/index.tsx

fix: dashboard initial resize incorrect

---

docs/_docs/zh/1.1-deployment.md
server/src/main/java/edp/core/utils/TokenUtils.java
server/src/main/java/edp/davinci/controller/DisplayController.java
server/src/main/java/edp/davinci/dto/displayDto/DisplayCopy.java
server/src/main/java/edp/davinci/service/DisplayService.java
server/src/main/java/edp/davinci/service/impl/DisplayServiceImpl.java

1. fix display copy
2. add doc of LDAP
3. fix token util log level

hotfix: display copy

---

docs/_docs/zh/1.1-deployment.md
server/src/main/java/edp/core/utils/TokenUtils.java
server/src/main/java/edp/davinci/controller/DisplayController.java
server/src/main/java/edp/davinci/dto/displayDto/DisplayCopy.java
server/src/main/java/edp/davinci/service/DisplayService.java
server/src/main/java/edp/davinci/service/impl/DisplayServiceImpl.java

1. fix display copy
2. add doc of LDAP
3. fix token util log level
(cherry picked from commit 69f1615908b7ef7db3b55f2c153347f82c473017)

fix: display copy

---

server/src/main/java/edp/davinci/service/impl/DownloadCommonService.java

fix: #1555

---

config/application.yml.example
server/pom.xml
server/src/main/java/edp/davinci/controller/LoginController.java
server/src/main/java/edp/davinci/core/config/WebSecurityConfig.java
server/src/main/java/edp/davinci/service/UserService.java
server/src/main/java/edp/davinci/service/impl/UserServiceImpl.java
webapp/app/containers/App/actions.ts
webapp/app/containers/App/constants.ts
webapp/app/containers/App/reducer.ts
webapp/app/containers/App/sagas.ts
webapp/app/containers/App/selectors.ts
webapp/app/containers/ExternalLogin/ExternalLogin.less
webapp/app/containers/ExternalLogin/index.tsx
webapp/app/containers/Login/index.tsx
webapp/app/containers/Main/index.tsx
webapp/app/utils/api.ts

Compatible with standard OAuth2 authentication services, corporate WeChat, Dingding, Feishu, etc.Because they use their own protocols, they are not yet compatible

New feature: support for OAuth2 authentication

---

webapp/app/containers/App/sagas.ts

Oauth2 login missing user information bug

fix: Oauth2 login missing user information bug

---

server/src/main/java/edp/davinci/model/RelUserOrganization.java
server/src/main/java/edp/davinci/service/impl/LdapServiceImpl.java
server/src/main/java/edp/davinci/service/impl/OrganizationServiceImpl.java
server/src/main/java/edp/davinci/service/impl/UserServiceImpl.java
server/src/main/resources/mybatis/mapper/RelUserOrganizationMapper.xml

fix: RelUserOrganization not save create info

---

webapp/app/containers/View/Editor.tsx
webapp/app/containers/View/components/SqlEditor.tsx

Cmd-Enter and Ctrl-Enter
executeSql

feature: sql editer add shortcut key

---

config/logback.xml
server/src/main/java/edp/core/common/quartz/QuartzJobExecutor.java

CronJob maybe executed multiple times

---

server/src/main/java/edp/core/utils/SqlUtils.java

as you can see,when my datasource is chickhoust and  i get tables , i can't filter the database as i chooese,i return all the datables's tables

getDBSchemaPattern add chlickhouse type support

---

server/src/main/java/edp/core/utils/MD5Util.java
server/src/main/java/edp/davinci/dto/cronJobDto/CronJobConfig.java
server/src/main/java/edp/davinci/service/impl/BaseScheduleService.java
server/src/main/java/edp/davinci/service/impl/CronJobServiceImpl.java
server/src/main/java/edp/davinci/service/impl/EmailScheduleServiceImpl.java
server/src/main/java/edp/davinci/service/impl/WeChatWorkScheduleServiceImpl.java
webapp/app/containers/Schedule/Editor.tsx
webapp/app/containers/Schedule/actions.ts
webapp/app/containers/Schedule/components/ScheduleBaseConfig/index.tsx
webapp/app/containers/Schedule/components/ScheduleWeChatWorkConfig.tsx
webapp/app/containers/Schedule/components/types.ts
webapp/app/containers/Schedule/constants.ts
webapp/app/containers/Schedule/reducer.ts

New feature: WeChat Work robot message push

New feature: WeChat Work robot message push

---

webapp/app/containers/Login/Login.less
webapp/app/containers/Login/LoginForm.tsx
webapp/app/containers/Login/index.tsx

Chore: adjust login styles

---

webapp/app/components/RelativeDatePicker/constants.ts
webapp/app/components/RelativeDatePicker/index.tsx
webapp/app/components/RelativeDatePicker/type.ts

Feat: RelativeDatePicker

---

server/src/main/java/edp/davinci/common/utils/ScriptUtiils.java
server/src/main/resources/templates/js/formatCellValue.js

bug fix: ScriptUtils.formatHeader

bug fix: ScriptUtils.formatHeader

---

webapp/app/containers/Organizations/Organization.tsx
webapp/app/containers/Organizations/Team.less
webapp/app/containers/Organizations/actions.ts
webapp/app/containers/Organizations/component/AddForm.tsx
webapp/app/containers/Organizations/component/MemberList.tsx
webapp/app/containers/Organizations/reducer.ts
webapp/app/containers/Organizations/sagas.ts
webapp/app/containers/Organizations/selectors.ts
webapp/app/containers/Organizations/types.ts

feat:(members) #1708

---

webapp/share/containers/Dashboard/index.tsx

fix(shareparam) #1796

---

.gitignore
assembly/src/main/assembly/assembly.xml
bin/davinci.sql

Add guest user

---

webapp/app/containers/Organizations/component/ProjectAdmin.tsx
webapp/app/containers/Organizations/component/ProjectRole.tsx
webapp/app/containers/Organizations/component/Transfer.tsx
webapp/app/containers/Widget/components/Workbench/FilterSettingForm.tsx

fix: Project related role transfer search unavailable

---

server/src/main/java/edp/davinci/dao/RelRoleDashboardMapper.java
server/src/main/java/edp/davinci/dao/RelRoleDashboardWidgetMapper.java
server/src/main/java/edp/davinci/dao/RelRoleDisplayMapper.java
server/src/main/java/edp/davinci/dao/RelRoleDisplaySlideWidgetMapper.java
server/src/main/java/edp/davinci/dao/RelRolePortalMapper.java
server/src/main/java/edp/davinci/dao/RelRoleSlideMapper.java
server/src/main/java/edp/davinci/dao/RelRoleViewMapper.java
server/src/main/java/edp/davinci/service/impl/DashboardServiceImpl.java
server/src/main/java/edp/davinci/service/impl/DisplayServiceImpl.java
server/src/main/java/edp/davinci/service/impl/RoleServiceImpl.java

Fix: Delete project role problem but the auth of view still take effect

---

assembly/pom.xml
config/application.yml.example
pom.xml
server/pom.xml
server/src/main/java/edp/core/config/RestClientConfig.java
server/src/main/java/edp/davinci/core/utils/DacChannelUtil.java
server/src/main/java/edp/davinci/core/utils/SqlParseUtils.java
server/src/main/java/edp/davinci/service/impl/WeChatWorkScheduleServiceImpl.java

RestTemplate support proxy

---

webapp/app/containers/Display/Editor/SlideEditor.tsx
webapp/app/containers/Display/Editor/SlideLayerList.tsx
webapp/app/containers/Display/actions.ts
webapp/app/containers/Display/components/Container/Container.less
webapp/app/containers/Display/components/Layer/Content/LayerBox.tsx
webapp/app/containers/Display/components/Layer/Content/LayerPositionTip.tsx
webapp/app/containers/Display/components/Layer/Draggable/LayerDraggable.tsx
webapp/app/containers/Display/components/Layer/LayerItem.tsx
webapp/app/containers/Display/components/Layer/types.ts
webapp/app/containers/Display/constants.ts
webapp/app/containers/Display/reducer.ts
webapp/app/containers/Display/sagas.ts

1 refactor(display): remove antd tooltip fix layerBox repeat rendering
2 refactor(display): layerBox keyDown move bug and remove dragLayerIndependence action

refactor display drayLayer performance

---

config/application.yml.example
server/src/main/java/edp/davinci/service/impl/ShareServiceImpl.java
server/src/main/java/edp/davinci/service/share/aspect/ShareAuthAspect.java
server/src/main/resources/mybatis/mapper/RelRoleUserMapper.xml

Fix: Some issues with share

---

webapp/app/containers/Schedule/Editor.tsx
webapp/app/containers/Schedule/components/ScheduleBaseConfig/ScheduleBaseConfig.less
webapp/app/containers/Schedule/components/ScheduleBaseConfig/index.tsx
webapp/app/containers/Schedule/components/types.ts
webapp/app/containers/Schedule/constants.ts
webapp/app/containers/Schedule/sagas.ts
webapp/app/utils/migrationRecorders/index.ts
webapp/app/utils/migrationRecorders/scheduleConfig.ts

refactor(Schedule): allow user to add cron expression manually

---

server/src/main/java/edp/core/utils/SqlUtils.java

Fix: Paging query issue

---

webapp/app/components/DataDrill/types.ts
webapp/app/containers/Dashboard/sagas.ts
webapp/app/containers/Dashboard/types.ts
webapp/app/containers/Dashboard/util.ts
webapp/app/containers/View/sagas.ts
webapp/app/containers/Viz/util.ts
webapp/app/containers/Widget/components/Widget/index.tsx
webapp/app/containers/Widget/components/Workbench/OperatingPanel.tsx
webapp/app/containers/Widget/components/Workbench/index.tsx
webapp/app/utils/migrationRecorders/widgetConfig.ts
webapp/share/containers/Dashboard/sagas.ts
webapp/share/containers/Display/sagas.ts

fix(Widget): remove 600 data limit

---

server/src/main/java/edp/davinci/core/utils/SourcePasswordEncryptUtils.java

feat:(table) optimize source table encryption function

feat:(table) optimize source table encryption function

---

webapp/app/containers/App/reducer.ts
webapp/app/containers/Display/components/Setting/Form/types.ts
webapp/app/containers/Display/components/util.ts
webapp/app/containers/Display/reducer.ts
webapp/app/containers/Display/sagas.ts
webapp/app/containers/Display/selectors.ts
webapp/app/containers/View/Editor.tsx
webapp/app/containers/View/reducer.ts
webapp/app/containers/Viz/reducer.ts
webapp/jest.config.js
webapp/test/app/containers/Display/actions.test.ts
webapp/test/app/containers/Display/fixtures.ts
webapp/test/app/containers/Display/reducer.test.ts
webapp/test/app/containers/Display/sagas.test.ts
webapp/test/app/containers/Display/selectors.test.ts
webapp/test/mocks/font.js

feat: add display unit test

---

webapp/app/containers/Widget/components/Chart/Table/index.tsx
webapp/app/containers/Widget/components/Chart/Table/util.ts

refactor(Table Widget): Change the logic of auto merge cells to group merge(pivot style)

---

webapp/app/containers/Display/components/Layer/RichText/index.tsx

fix: display preview bug

---

webapp/app/components/DataDrill/abstract/widgetOperating.ts
webapp/app/containers/Dashboard/sagas.ts
webapp/share/containers/Dashboard/sagas.ts

fix(drill) #1971

---

server/src/main/java/edp/davinci/service/impl/LdapServiceImpl.java

Using LDAP server's mail attribute instead of the local variable "userDn"

Fetch mail from ldap server

---

server/src/main/java/edp/davinci/common/utils/ScriptUtils.java
server/src/main/java/edp/davinci/core/utils/ExcelUtils.java
server/src/main/java/edp/davinci/core/utils/VizUtils.java
server/src/main/java/edp/davinci/dto/viewDto/ViewExecuteParam.java
server/src/main/java/edp/davinci/service/excel/WidgetContext.java
server/src/main/java/edp/davinci/service/excel/WorkBookContext.java
server/src/main/java/edp/davinci/service/excel/WorkbookWorker.java
server/src/main/java/edp/davinci/service/impl/DownloadCommonService.java
server/src/main/java/edp/davinci/service/impl/DownloadServiceImpl.java
server/src/main/java/edp/davinci/service/impl/EmailScheduleServiceImpl.java
server/src/main/java/edp/davinci/service/impl/ShareDownloadServiceImpl.java
server/src/main/java/edp/davinci/service/impl/ShareServiceImpl.java
server/src/main/java/edp/davinci/service/impl/ViewServiceImpl.java
server/src/main/java/edp/davinci/service/impl/WidgetServiceImpl.java
server/src/main/resources/templates/js/executeParam.js

Fix: issue 2006 & 2007

---

webapp/app/containers/Display/sagas.ts
webapp/app/containers/Widget/components/Workbench/ConfigSections/DoubleYAxisSection.tsx
webapp/app/containers/Widget/components/util.ts
webapp/app/containers/Widget/render/chart/doubleYAxis.ts
webapp/app/containers/Widget/render/chart/helper.ts
webapp/internals/webpack/webpack.base.babel.js

feat: add doubleY decimal and negative number

feat: add doubleY decimal and negative number

---

config/application.yml.example
server/src/main/java/edp/core/utils/SqlUtils.java
server/src/main/java/edp/davinci/controller/HomeController.java
server/src/main/java/edp/davinci/core/enums/SqlOperatorEnum.java
server/src/main/java/edp/davinci/core/model/Criterion.java
server/src/main/java/edp/davinci/core/model/SqlFilter.java
server/src/main/java/edp/davinci/core/utils/SourcePasswordEncryptUtils.java
server/src/main/java/edp/davinci/service/impl/ViewServiceImpl.java

Fix: Global controller include or no include does not take effect

---

webapp/app/containers/Display/Preview/Reveal.tsx
webapp/package.json
webapp/share/containers/Display/Reveal/Reveal.tsx

Update dependency reveal.js@^4.1.0 to fix #2032

fix(Display): #2032

---

webapp/app/containers/Widget/render/chart/doubleYAxis.ts
webapp/app/containers/Widget/render/chart/helper.ts

fix: doubleY decimal point bug

fix: doubleY decimal point bug

---

server/src/main/java/edp/davinci/controller/WidgetController.java
server/src/main/java/edp/davinci/dao/WidgetMapper.java
server/src/main/java/edp/davinci/dto/widgetDto/WidgetWithViewName.java
server/src/main/java/edp/davinci/service/WidgetService.java
server/src/main/java/edp/davinci/service/impl/WidgetServiceImpl.java
webapp/app/containers/Widget/List.tsx
webapp/app/containers/Widget/components/Widget/index.tsx
webapp/app/containers/Widget/reducer.ts
webapp/app/containers/Widget/types.ts

Add type icon and related view name to widget list

enhancement: Add type icon and related view name to widget list

---

server/src/main/java/edp/davinci/controller/OrganizationController.java
server/src/main/java/edp/davinci/dto/organizationDto/BatchInviteMemberResult.java
server/src/main/java/edp/davinci/dto/organizationDto/InviteMembers.java
server/src/main/java/edp/davinci/service/OrganizationService.java
server/src/main/java/edp/davinci/service/impl/OrganizationServiceImpl.java
webapp/app/containers/Organizations/Organization.less
webapp/app/containers/Organizations/component/AddForm.tsx
webapp/app/containers/Organizations/component/MemberList.tsx
webapp/app/containers/Organizations/component/NotUsersList.tsx
webapp/app/containers/Organizations/sagas.ts
webapp/app/containers/Organizations/types.ts

- Support word segmentation search(Separate with commas and semicolons)
- Support multiple selection

enhancement: Invite user panel

---

server/src/main/java/edp/davinci/service/screenshot/ScreenshotUtil.java

Enhancement: Chrome driver 'disable-dev-shm-usage' argument

---

webapp/app/containers/Widget/components/Workbench/ConfigSections/DoubleYAxisSection.tsx
webapp/app/containers/Widget/render/chart/helper.ts

fix: add interval precision

---

webapp/app/containers/Display/components/Layer/Content/LayerBox.tsx
webapp/app/containers/Display/components/Layer/Content/LayerTooltip.tsx
webapp/app/containers/Display/components/Layer/Content/SecondaryGraph/Video.tsx
webapp/app/containers/Display/components/Layer/Content/SecondaryGraph/constants.ts
webapp/app/containers/Display/components/Setting/Form/Form.tsx
webapp/app/containers/Display/components/Setting/Form/Item.tsx
webapp/app/containers/Display/components/Setting/Form/ItemGroup.tsx

feat: add video support iframe

feat: add video support iframe

---

webapp/app/components/CheckPanel/CheckPanel.less
webapp/app/components/CheckPanel/index.tsx
webapp/app/components/CheckPanel/types.ts
webapp/app/components/CheckPanel/utils.ts
webapp/app/containers/Organizations/component/RoleList.tsx

- Support word segmentation search
- Make it bigger

enhancement: Role-related-members transfer component enhancement

---

webapp/app/containers/Dashboard/util.ts

fix(utils): bugs when withPaging==false set pageNo=0 pageSize=0

fix(utils): bugs when withPaging==false set pageNo=0 pageSize=0

---

server/pom.xml
server/src/main/java/edp/core/common/jdbc/JdbcDataSource.java
server/src/main/java/edp/core/config/DruidConfig.java
server/src/main/java/edp/core/model/JdbcSourceInfo.java
server/src/main/java/edp/core/utils/CustomDataSourceUtils.java
server/src/main/java/edp/core/utils/SourceUtils.java
server/src/main/java/edp/core/utils/SqlUtils.java
server/src/main/java/edp/davinci/core/enums/SourceTypeEnum.java
server/src/main/java/edp/davinci/core/utils/SqlParseUtils.java
server/src/main/java/edp/davinci/dto/userDto/SendMail.java
server/src/main/java/edp/davinci/service/excel/AbstractSheetWriter.java
server/src/main/java/edp/davinci/service/impl/SourceServiceImpl.java
server/src/main/java/edp/davinci/service/impl/StatisticServiceImpl.java
server/src/test/.gitignore

Fix: Allow sql use comment

---

server/src/main/java/edp/davinci/service/impl/ViewServiceImpl.java

 Fix: Modify view use wrong source to test

---

server/src/main/java/edp/core/common/jdbc/JdbcDataSource.java
server/src/main/java/edp/core/common/quartz/QuartzJobExecutor.java
server/src/main/java/edp/core/utils/SqlUtils.java
server/src/main/java/edp/davinci/core/utils/SqlParseUtils.java
server/src/main/java/edp/davinci/service/excel/ExecutorUtils.java
server/src/main/java/edp/davinci/service/excel/WorkbookWorker.java
server/src/main/java/edp/davinci/service/impl/CronJobServiceImpl.java
server/src/main/java/edp/davinci/service/impl/DownloadServiceImpl.java
server/src/main/java/edp/davinci/service/impl/EmailScheduleServiceImpl.java
server/src/main/java/edp/davinci/service/impl/ShareDownloadServiceImpl.java
server/src/main/java/edp/davinci/service/impl/ViewServiceImpl.java
server/src/main/java/edp/davinci/service/impl/WidgetServiceImpl.java
server/src/main/resources/application.yml

Enhancement: SQL syntax is not supported

---

server/src/main/java/edp/davinci/dao/RelRoleDashboardMapper.java
server/src/main/java/edp/davinci/dao/RelRoleDashboardWidgetMapper.java
server/src/main/java/edp/davinci/dao/RelRoleDisplayMapper.java
server/src/main/java/edp/davinci/dao/RelRoleDisplaySlideWidgetMapper.java
server/src/main/java/edp/davinci/dao/RelRolePortalMapper.java
server/src/main/java/edp/davinci/dao/RelRoleSlideMapper.java
server/src/main/java/edp/davinci/dao/RelRoleViewMapper.java

1：解决数据操作传递参数缺少@Param注解，mybatis传参需要确定param命名

perft:删除应用关联角色接口-报错优化

---

bin/davinci.sql

Fix: Table `cron_job` UNIQUE KEY fault

---

bin/davinci.sql
data/src/main/java/edp/davinci/data/pojo/Filter.java
server/src/main/java/edp/davinci/server/dto/view/WidgetQueryParam.java
server/src/main/java/edp/davinci/server/model/ExcelHeader.java

Fix: Excel generate error
